# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

#strategy:
#  matrix:
#    linux:
#      imageName: 'ubuntu-latest'
#    mac:
#      imageName: 'macos-10.13'
#    windows:
#      imageName: 'windows-latest'


#pool:
#  vmImage: '$(imageName)'

jobs:
- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - script: |
      dir
      .\mvnw verify -Djpt.btf.provision=true
    displayName: 'Run all-the-things!'
#- job: macOS
#  pool:
#    vmImage: 'macOS-10.13'
#  steps:
#  - script: echo hello from macOS
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      ./mvnw verify -Djpt.btf.provision=true
    displayName: 'Run all-the-things!'

#steps:
#- bash: |
#    ./mvnw verify -Djpt.btf.provision=true
#  displayName: 'Run all-the-things!'
