# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
#    mac:
#      imageName: 'macos-10.13'
    windows:
      imageName: 'windows-latest'


pool:
  vmImage: '$(imageName)'

steps:
- script: |
    ./mvnw verify -Djpt.btf.provision=true
  displayName: 'Run all-the-things!'
